---
dist: xenial

language: python

python:
  - "3.6"
  - "3.7"

services:
  - docker

install:
  - pip install pipenv==2018.11.26
  - pipenv sync --dev

script:
  - pipenv run molecule test

notifications:
  webhooks:
    - https://galaxy.ansible.com/api/v1/notifications/
