---
- name: Check for existing Helm installation
  stat:
    path: /usr/local/bin/helm
  register: stat_helm_result

- name: Check Helm version
  command: helm version
  changed_when: no
  failed_when: no
  register: helm_version_result
  when: stat_helm_result.stat.exists

- name: Include Helm installtion tasks
  become: yes
  include_tasks: install.yml
  when: not stat_helm_result.stat.exists or
        helm_version_result.stdout_lines | first | regex_search('[0-9]+\\.[0-9]+\\.[0-9]+') != helm_version
